In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [3]:
dataset=pd.read_csv('../datasets/customer_churn.csv')
dataset.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2865980.0,43.0,Male,42.0,8.0,8.0,25.0,Standard,Annual,136.99,23.0,1.0
1,2620238.0,23.0,Female,60.0,12.0,5.0,3.0,Basic,Annual,843.14,17.0,1.0
2,4434988.0,58.0,Male,54.0,10.0,0.0,10.0,Standard,Quarterly,429.39,27.0,0.0
3,8341795.0,47.0,Male,35.0,6.0,9.0,24.0,Premium,Quarterly,639.84,24.0,1.0
4,5485334.0,26.0,Male,45.0,21.0,4.0,1.0,Basic,Quarterly,761.42,13.0,0.0

In [4]:
from sklearn.preprocessing import OneHotEncoder

In [5]:
dataset=pd.get_dummies(dataset,columns=['Gender'],drop_first=True)
dataset.head()

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn,Gender_Male
0,2865980.0,43.0,42.0,8.0,8.0,25.0,Standard,Annual,136.99,23.0,1.0,True
1,2620238.0,23.0,60.0,12.0,5.0,3.0,Basic,Annual,843.14,17.0,1.0,False
2,4434988.0,58.0,54.0,10.0,0.0,10.0,Standard,Quarterly,429.39,27.0,0.0,True
3,8341795.0,47.0,35.0,6.0,9.0,24.0,Premium,Quarterly,639.84,24.0,1.0,True
4,5485334.0,26.0,45.0,21.0,4.0,1.0,Basic,Quarterly,761.42,13.0,0.0,True

In [6]:
dataset = dataset.dropna()
dataset.drop(columns=['CustomerID'],inplace=True)
from sklearn.preprocessing import MinMaxScaler
MS=MinMaxScaler()
cols=['Age','Usage Frequency','Support Calls','Payment Delay','Total Spend','Last Interaction']

dataset[cols]=MS.fit_transform(dataset[cols])

In [7]:
dataset.head()

,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn,Gender_Male
0,0.531915,42.0,0.241379,0.8,0.827586,Standard,Annual,0.041100,0.758621,1.0,True
1,0.106383,60.0,0.379310,0.5,0.068966,Basic,Annual,0.825711,0.551724,1.0,False
2,0.851064,54.0,0.310345,0.0,0.310345,Standard,Quarterly,0.365989,0.896552,0.0,True
3,0.617021,35.0,0.172414,0.9,0.793103,Premium,Quarterly,0.599822,0.793103,1.0,True
4,0.170213,45.0,0.689655,0.4,0.000000,Basic,Quarterly,0.734911,0.413793,0.0,True

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

dataset['Subscription Type'] = le.fit_transform(dataset['Subscription Type'])
dataset['Contract Length'] = le.fit_transform(dataset['Contract Length'])

In [9]:
dataset.head()

,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn,Gender_Male
0,0.531915,42.0,0.241379,0.8,0.827586,2,0,0.041100,0.758621,1.0,True
1,0.106383,60.0,0.379310,0.5,0.068966,0,0,0.825711,0.551724,1.0,False
2,0.851064,54.0,0.310345,0.0,0.310345,2,2,0.365989,0.896552,0.0,True
3,0.617021,35.0,0.172414,0.9,0.793103,1,2,0.599822,0.793103,1.0,True
4,0.170213,45.0,0.689655,0.4,0.000000,0,2,0.734911,0.413793,0.0,True

In [10]:
print(dataset.columns)

Index(['Age', 'Tenure', 'Usage Frequency', 'Support Calls', 'Payment Delay',
       'Subscription Type', 'Contract Length', 'Total Spend',
       'Last Interaction', 'Churn', 'Gender_Male'],
      dtype='str')

In [11]:
X = dataset.drop("Churn", axis=1)
y = dataset["Churn"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [12]:
X_train

,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Gender_Male
566853,0.361702,30.0,0.241379,0.5,0.896552,1,2,0.351800,0.413793,False
382311,0.553191,11.0,0.482759,0.4,0.034483,1,2,0.367322,0.965517,False
241519,0.446809,26.0,0.103448,0.0,0.965517,2,0,0.906611,0.862069,False
719220,0.914894,55.0,0.517241,0.9,0.344828,2,2,0.690656,0.758621,True
905718,0.851064,11.0,0.965517,0.5,0.000000,2,0,0.888556,0.896552,False
...,...,...,...,...,...,...,...,...,...,...
259178,0.808511,26.0,0.482759,0.4,0.965517,0,1,0.710878,0.206897,False
365838,0.510638,51.0,0.413793,0.5,0.241379,1,2,0.916889,0.448276,False
131932,0.021277,54.0,0.000000,0.6,0.034483,1,2,0.734233,0.068966,True
671155,0.191489,57.0,0.241379,0.1,0.172414,0,0,0.836178,0.379310,False
121958,0.212766,58.0,0.068966,0.2,0.448276,1,0,0.608456,0.586207,True

In [13]:
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [14]:
y_pred = model.predict(X_test)
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.65797

In [15]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[45351 41026]
 [27380 86243]]

In [16]:
from sklearn.metrics import recall_score
print("Recall:", recall_score(y_test, y_pred))

Recall: 0.7590276616530104

In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.62      0.53      0.57     86377
         1.0       0.68      0.76      0.72    113623

    accuracy                           0.66    200000
   macro avg       0.65      0.64      0.64    200000
weighted avg       0.65      0.66      0.65    200000

In [18]:
print(dataset['Churn'].value_counts())

Churn
1.0    567151
0.0    432849
Name: count, dtype: int64

In [19]:
y_prob = model.predict_proba(X_test)[:,1]
y_pred = (y_prob > 0.55).astype(int)

In [20]:
from sklearn.metrics import accuracy_score, recall_score

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))

Accuracy: 0.65229
Recall: 0.6748897670366035

In [21]:
for t in [0.4, 0.5, 0.55, 0.6, 0.65]:
    y_pred = (y_prob > t).astype(int)
    print("Threshold:", t)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Recall:", recall_score(y_test, y_pred))
    print()

Threshold: 0.4
Accuracy: 0.644185
Recall: 0.8883940751432369

Threshold: 0.5
Accuracy: 0.65797
Recall: 0.7590276616530104

Threshold: 0.55
Accuracy: 0.65229
Recall: 0.6748897670366035

Threshold: 0.6
Accuracy: 0.6379
Recall: 0.5803402480131663

Threshold: 0.65
Accuracy: 0.61415
Recall: 0.4752030838826646

In [22]:
from sklearn.metrics import accuracy_score

y_train_pred = model.predict(X_train)

print("Train Accuracy:", accuracy_score(y_train, y_train_pred))
print("Test Accuracy:", accuracy_score(y_test, y_pred))

Train Accuracy: 0.65732125
Test Accuracy: 0.61415

In [23]:
'''' Index(['CustomerID', 'Age', 'Tenure', 'Usage Frequency', 'Support Calls',
       'Payment Delay', 'Subscription Type', 'Contract Length', 'Total Spend',
       'Last Interaction', 'Churn', 'Gender_Male'],
      dtype='str')'''

"' Index(['CustomerID', 'Age', 'Tenure', 'Usage Frequency', 'Support Calls',\n       'Payment Delay', 'Subscription Type', 'Contract Length', 'Total Spend',\n       'Last Interaction', 'Churn', 'Gender_Male'],\n      dtype='str')"

In [24]:
new_customer = pd.DataFrame({
    'Age': [30],
    'Usage Frequency': [0.5],
    'Support Calls': [3],
    'Payment Delay': [1],
    'Total Spend': [0.4],
    'Last Interaction': [0.6],
    'Gender_1': [1]   # 1 = Male (depending on your encoding)
})

In [25]:
new_customer = pd.DataFrame({
    'Age': [0.5],
    'Tenure': [30],
    'Usage Frequency': [0.4],
    'Support Calls': [0.6],
    'Payment Delay': [0.2],
    'Subscription Type': [1],
    'Contract Length': [2],
    'Total Spend': [0.7],
    'Last Interaction': [0.3],
    'Gender_Male': [1]
})

In [29]:
prediction = model.predict(new_customer)

print("Prediction:", prediction)

Prediction: [0.]